
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: solution.ipynb

import numpy as np
from helper_functions import *

def get_initial_means(array, k):
    """
    Picks k random points from the 2D array
    (without replacement) to use as initial
    cluster means

    params:
    array = numpy.ndarray[numpy.ndarray[float]] - m x n | datapoints x features

    k = int

    returns:
    initial_means = numpy.ndarray[numpy.ndarray[float]]
    """
    # TODO: finish this function
    m=np.size(array,0)
    initial=np.random.choice(m,k,replace=False)
    return array[initial]

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def k_means_step(X, k, means):
    """
    A single update/step of the K-means algorithm
    Based on a input X and current mean estimate
    calculate new means and predict clusters for each of the pixel
    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n | pixels x features (already flattened)
    k = int
    means = numpy.ndarray[numpy.ndarray[float]] - k x n

    returns:
    (new_means, clusters)
    new_means = numpy.ndarray[numpy.ndarray[float]] - k x n
    clusters = numpy.ndarray[int] - m sized vector
    """
    # TODO: finish this function
    m=np.size(X,0)
    z=np.sum(np.square(X),axis=1)
    t=np.sum(np.square(means),axis=1)
    d=np.sqrt(np.reshape(z,(m,1))+np.reshape(t,(1,k))-np.dot(X,means.T)*2)
    clusters=np.argmin(d,axis=1)
    n=np.size(X,1)
    new_means=np.zeros((k,n))
    for i in range(k):
        XinCenter=X[clusters==i]
        new_means[i,:]=np.mean(XinCenter,axis=0)
    return (new_means,clusters)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def k_means_segment(image_values, k=3, initial_means=None):
    """
    Separate the provided RGB values into
    k separate clusters using the k-means algorithm,
    then return an updated version of the image
    with the original values replaced with
    the corresponding cluster values.

    params:
    image_values = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - r x c x ch
    k = int
    initial_means = numpy.ndarray[numpy.ndarray[float]] or None

    returns:
    updated_image_values = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - r x c x ch
    """
    # TODO: finish this function
    r, c, ch = image_values.shape
    flat_img = np.reshape(image_values, [-1, ch])
    if np.size(initial_means)==1:
        initial_means=get_initial_means(flat_img,k)
    old_means=initial_means
    (new_means,clusters)=k_means_step(flat_img, k,old_means)
    while np.sum(old_means-new_means)!=0:
        old_means=new_means
        (new_means,clusters)=k_means_step(flat_img, k,old_means)
    updated_image_values=np.reshape(new_means[clusters], (r, c, ch))
    return updated_image_values



########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def initialize_parameters(X, k):
    """
    Return initial values for training of the GMM
    Set component mean to a random
    pixel's value (without replacement),
    based on the mean calculate covariance matrices,
    and set each component mixing coefficient (PIs)
    to a uniform values
    (e.g. 4 components -> [0.25,0.25,0.25,0.25]).

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    k = int

    returns:
    (MU, SIGMA, PI)
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    PI = numpy.ndarray[float] - k x 1
    """
    # TODO: finish this function
    PI=np.ones(k)/k
    m=np.size(X,0)
    n=np.size(X,1)
    initial=np.random.choice(m,k,replace=False)
    MU=X[initial]
    SIGMA=np.zeros((k,n,n))
    for i in range(k):
        SIGMA[i,:,:]=np.dot((X-MU[i,:]).T,(X-MU[i,:]))/m
    return (MU,SIGMA,PI)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def prob(x, mu, sigma):
    """Calculate the probability of a single
    data point x under component with
    the given mean and covariance.
    # NOTE: there is nothing to vectorize here yet,
    # it's a simple check to make sure you got the
    # multivariate normal distribution formula right
    # which is given by N(x;MU,SIGMA) above

    params:
    x = numpy.ndarray[float]
    mu = numpy.ndarray[float]
    sigma = numpy.ndarray[numpy.ndarray[float]]

    returns:
    probability = float
    """
    # TODO: finish this function
    D=np.size(x)
    diff=x-mu
    det=np.linalg.det(sigma)
    sigma_inv=np.linalg.inv(sigma)
    p=np.exp(-0.5*np.dot(np.dot(diff,sigma_inv),diff))/(np.sqrt(np.absolute(det))*(np.power(2*np.pi,D/2)))
    return p

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def E_step(X,MU,SIGMA,PI,k):
    """
    E-step - Expectation
    Calculate responsibility for each
    of the data points, for the given
    MU, SIGMA and PI.

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    PI = numpy.ndarray[float] - k x 1
    k = int

    returns:
    responsibility = numpy.ndarray[numpy.ndarray[float]] - k x m
    """
    # TODO: finish this function
    m,n=X.shape
    responsibility=np.zeros((k,m))
    for i in range(k):
        diff=X-MU[i,:]
        sigmai=SIGMA[i,:,:]
        det=np.linalg.det(sigmai)
        inv=np.linalg.inv(sigmai)
        responsibility[i,:]=PI[i]*np.exp(np.sum(-0.5*np.dot(diff,inv)*diff,axis=1))/(np.sqrt(np.absolute(det))*(np.power(2*np.pi,n/2)))
    return responsibility/np.sum(responsibility,axis=0)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def M_step(X, r, k):
    """
    M-step - Maximization
    Calculate new MU, SIGMA and PI matrices
    based on the given responsibilities.

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    r = numpy.ndarray[numpy.ndarray[float]] - k x m
    k = int

    returns:
    (new_MU, new_SIGMA, new_PI)
    new_MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    new_SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    new_PI = numpy.ndarray[float] - k x 1
    """
    # TODO: finish this function
    m,n=X.shape
    new_MU=np.zeros((k,n))
    new_PI=np.zeros(k)
    new_SIGMA=np.zeros((k,n,n))
    for i in range(k):
        Nk=np.sum(r[i,:])
        mu_num=np.sum(np.reshape(r[i,:],(m,1))*X,axis=0)
        new_MU[i,:]=mu_num/Nk
        new_PI[i]=Nk/m
        diff=X-new_MU[i,:]
        new_SIGMA[i,:,:]=np.dot(r[i,:]*diff.T,diff)/Nk
    return (new_MU, new_SIGMA, new_PI)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def likelihood(X, PI, MU, SIGMA, k):
    """Calculate a log likelihood of the
    trained model based on the following
    formula for posterior probability:

    log10(Pr(X | mixing, mean, stdev)) = sum((n=1 to N), log10(sum((k=1 to K),
                                      mixing_k * N(x_n | mean_k,stdev_k))))

    Make sure you are using log base 10, instead of log base 2.

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    PI = numpy.ndarray[float] - k x 1
    k = int

    returns:
    log_likelihood = float
    """
    # TODO: finish this function
    m,n=X.shape
    prob=np.zeros((k,m))
    for i in range(k):
        diff=X-MU[i,:]
        sigmai=SIGMA[i,:,:]
        det=np.linalg.det(sigmai)
        inv=np.linalg.inv(sigmai)
        prob[i,:]=PI[i]*np.exp(np.sum(-0.5*np.dot(diff,inv)*diff,axis=1))/(np.sqrt(np.absolute(det))*(np.power(2*np.pi,n/2)))
    return np.sum(np.log10(np.sum(prob,axis=0)))

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def train_model(X, k, convergence_function, initial_values = None):
    """
    Train the mixture model using the
    expectation-maximization algorithm.
    E.g., iterate E and M steps from
    above until convergence.
    If the initial_values are None, initialize them.
    Else it's a tuple of the format (MU, SIGMA, PI).
    Convergence is reached when convergence_function
    returns terminate as True,
    see default convergence_function example
    in `helper_functions.py`

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    k = int
    convergence_function = func
    initial_values = None or (MU, SIGMA, PI)

    returns:
    (new_MU, new_SIGMA, new_PI, responsibility)
    new_MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    new_SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    new_PI = numpy.ndarray[float] - k x 1
    responsibility = numpy.ndarray[numpy.ndarray[float]] - k x m
    """
    # TODO: finish this function
    m,n=X.shape
    if initial_values==None:
        initial_values=initialize_parameters(X, k)
    (MU,SIGMA,PI)=initial_values
    prev_likelihood=likelihood(X, PI, MU, SIGMA, k)
    r=E_step(X,MU,SIGMA,PI,k)
    (new_MU, new_SIGMA, new_PI)=M_step(X, r, k)
    new_likelihood=likelihood(X, new_PI, new_MU, new_SIGMA, k)
    count=0
    count,terminate=convergence_function(prev_likelihood,new_likelihood,count)
    while not terminate:
        (MU,SIGMA,PI)=(new_MU, new_SIGMA, new_PI)
        prev_likelihood=new_likelihood
        r=E_step(X,MU,SIGMA,PI,k)
        (new_MU, new_SIGMA, new_PI)=M_step(X, r, k)
        new_likelihood=likelihood(X, new_PI, new_MU, new_SIGMA, k)
        count,terminate=convergence_function(prev_likelihood,new_likelihood,count)
    return (new_MU, new_SIGMA, new_PI, r)


########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def cluster(r):
    """
    Based on a given responsibilities matrix
    return an array of cluster indices.
    Assign each datapoint to a cluster based,
    on component with a max-likelihood
    (maximum responsibility value).

    params:
    r = numpy.ndarray[numpy.ndarray[float]] - k x m - responsibility matrix

    return:
    clusters = numpy.ndarray[int] - m x 1
    """
    # TODO: finish this
    k,m=r.shape
    clusters=np.argmax(r,axis=0)
    return clusters

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def segment(X, MU, k, r):
    """
    Segment the X matrix into k components.
    Returns a matrix where each data point is
    replaced with its max-likelihood component mean.
    E.g., return the original matrix where each pixel's
    intensity replaced with its max-likelihood
    component mean. (the shape is still mxn, not
    original image size)

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    k = int
    r = numpy.ndarray[numpy.ndarray[float]] - k x m - responsibility matrix

    returns:
    new_X = numpy.ndarray[numpy.ndarray[float]] - m x n
    """
    # TODO: finish this function
    clusters=cluster(r)
    new_X=MU[clusters]
    return new_X

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def best_segment(X,k,iters):
    """Determine the best segmentation
    of the image by repeatedly
    training the model and
    calculating its likelihood.
    Return the segment with the
    highest likelihood.

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    k = int
    iters = int

    returns:
    (likelihood, segment)
    likelihood = float
    segment = numpy.ndarray[numpy.ndarray[float]]
    """
    # TODO: finish this function
    max_likelihood=float('-inf')
    initial_values=None
    res=[0]
    for i in range(iters):
        (new_MU, new_SIGMA, new_PI, r)=train_model(X, k, convergence_function=default_convergence, initial_values=initial_values)
        new_likelihood=likelihood(X, new_PI, new_MU, new_SIGMA, k)
        if new_likelihood>max_likelihood:
            max_likelihood=new_likelihood
            res[0]=np.copy(segment(X, new_MU, k, r))
        initial_values=(new_MU, new_SIGMA, new_PI)
    return (max_likelihood,res[0])


########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def improved_initialization(X,k):
    """
    Initialize the training
    process by setting each
    component mean using some algorithm that
    you think might give better means to start with,
    based on the mean calculate covariance matrices,
    and set each component mixing coefficient (PIs)
    to a uniform values
    (e.g. 4 components -> [0.25,0.25,0.25,0.25]).

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    k = int

    returns:
    (MU, SIGMA, PI)
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    PI = numpy.ndarray[float] - k x 1
    """
    # TODO: finish this function
    initial_means=get_initial_means(X,k)
    old_means=initial_means
    (new_means,clusters)=k_means_step(X, k,old_means)
    while np.sum(old_means-new_means)!=0:
        old_means=new_means
        (new_means,clusters)=k_means_step(X, k,old_means)
    PI=np.ones(k)/k
    m=np.size(X,0)
    n=np.size(X,1)
    initial=np.random.choice(m,k,replace=False)
    MU=new_means
    SIGMA=np.zeros((k,n,n))
    for i in range(k):
        SIGMA[i,:,:]=np.dot((X-MU[i,:]).T,(X-MU[i,:]))/m
    return (MU,SIGMA,PI)





########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def new_convergence_function(previous_variables, new_variables, conv_ctr,
                             conv_ctr_cap=10):
    """
    Convergence function
    based on parameters:
    when all variables vary by
    less than 10% from the previous
    iteration's variables, increase
    the convergence counter.

    params:
    previous_variables = [numpy.ndarray[float]]
                         containing [means, variances, mixing_coefficients]
    new_variables = [numpy.ndarray[float]]
                    containing [means, variances, mixing_coefficients]
    conv_ctr = int
    conv_ctr_cap = int

    return:
    (conv_crt, converged)
    conv_ctr = int
    converged = boolean
    """
    # TODO: finish this function
    a1=abs(previous_variables[0])*0.9<abs(new_variables[0])
    a2=abs(new_variables[0])<abs(previous_variables[0])*1.1
    b1=abs(previous_variables[1])*0.9<abs(new_variables[1])
    b2=abs(new_variables[1])<abs(previous_variables[1])*1.1
    c1=abs(previous_variables[2])*0.9<abs(new_variables[2])
    c2=abs(new_variables[2])<abs(previous_variables[2])*1.1
    increase_convergence_ctr = a1.all() and a2.all() and b1.all() and b2.all() and c1.all() and c2.all()
    if increase_convergence_ctr:
        conv_ctr += 1
    else:
        conv_ctr = 0

    return conv_ctr, conv_ctr > conv_ctr_cap

def train_model_improved(X, k, convergence_function, initial_values = None):
    """
    Train the mixture model using the
    expectation-maximization algorithm.
    E.g., iterate E and M steps from
    above until convergence.
    If the initial_values are None, initialize them.
    Else it's a tuple of the format (MU, SIGMA, PI).
    Convergence is reached when convergence_function
    returns terminate as True. Use new_convergence_fuction
    implemented above.

    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    k = int
    convergence_function = func
    initial_values = None or (MU, SIGMA, PI)

    returns:
    (new_MU, new_SIGMA, new_PI, responsibility)
    new_MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    new_SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    new_PI = numpy.ndarray[float] - k x 1
    responsibility = numpy.ndarray[numpy.ndarray[float]] - k x m
    """
    # TODO: finish this function
    m,n=X.shape
    if initial_values==None:
        initial_values=initialize_parameters(X, k)
    (MU,SIGMA,PI)=initial_values
    prev_variables=[MU,SIGMA,PI]
    r=E_step(X,MU,SIGMA,PI,k)
    (new_MU, new_SIGMA, new_PI)=M_step(X, r, k)
    new_variables=[new_MU, new_SIGMA, new_PI]
    count=0
    count,terminate=convergence_function(prev_variables,new_variables,count)
    while not terminate:
        (MU,SIGMA,PI)=(new_MU, new_SIGMA, new_PI)
        prev_variables=new_variables
        r=E_step(X,MU,SIGMA,PI,k)
        (new_MU, new_SIGMA, new_PI)=M_step(X, r, k)
        new_variables=[new_MU, new_SIGMA, new_PI]
        count,terminate=convergence_function(prev_variables,new_variables,count)
    return (new_MU, new_SIGMA, new_PI, r)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
# Unittest below will check both of the functions at the same time.
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def bayes_info_criterion(X, PI, MU, SIGMA, k):
    """
    See description above
    params:
    X = numpy.ndarray[numpy.ndarray[float]] - m x n
    MU = numpy.ndarray[numpy.ndarray[float]] - k x n
    SIGMA = numpy.ndarray[numpy.ndarray[numpy.ndarray[float]]] - k x n x n
    PI = numpy.ndarray[float] - k x 1
    k = int

    return:
    bayes_info_criterion = int
    """
    # TODO: finish this function
    m,n=X.shape
    return np.log(X.size) * n * k - 2 * likelihood(X, PI, MU, SIGMA, k)

########## DON'T WRITE ANY CODE OUTSIDE THE FUNCTION! ################
##### CODE BELOW IS USED FOR RUNNING LOCAL TEST DON'T MODIFY IT ######
################ END OF LOCAL TEST CODE SECTION ######################

def BIC_likelihood_model_test(image_matrix, comp_means):
    """Returns the number of components
    corresponding to the minimum BIC
    and maximum likelihood with respect
    to image_matrix and comp_means.

    params:
    image_matrix = numpy.ndarray[numpy.ndarray[float]] - m x n
    comp_means = list(numpy.ndarray[numpy.ndarray[float]]) - list(k x n) (means for each value of k)

    returns:
    (n_comp_min_bic, n_comp_max_likelihood)
    n_comp_min_bic = int
    n_comp_max_likelihood = int
    """
    # TODO: finish this method
    n_comp_min_bic=0
    min_bic=float('inf')
    n_comp_max_likelihood=0
    max_likelihood=float('-inf')
    m,n=image_matrix.shape
    for i in range(len(comp_means)):
        MU=comp_means[i]
        k=np.size(MU,axis=0)
        PI=np.ones(k)/k
        SIGMA=np.zeros((k,n,n))
        for i in range(k):
            SIGMA[i,:,:]=np.dot((image_matrix-MU[i,:]).T,(image_matrix-MU[i,:]))/m
        (new_MU, new_SIGMA, new_PI, r)=train_model_improved(image_matrix, k, new_convergence_function, initial_values = (MU,SIGMA,PI))
        bic=bayes_info_criterion(image_matrix,new_PI, new_MU, new_SIGMA, k)
        if bic<min_bic:
            min_bic=bic
            n_comp_min_bic=k
        the_likelihood=likelihood(image_matrix, new_PI, new_MU, new_SIGMA, k)
        if the_likelihood>max_likelihood:
            max_likelihood=the_likelihood
            n_comp_max_likelihood=k
    return (n_comp_min_bic, n_comp_max_likelihood)


def return_your_name():
    # return your name
    # TODO: finish this
    return "Xufan Song"

def bonus(points_array, means_array):
    """
    Return the distance from every point in points_array
    to every point in means_array.

    returns:
    dists = numpy array of float
    """
    # TODO: fill in the bonus function
    # REMOVE THE LINE BELOW IF ATTEMPTING BONUS
    row_x=np.size(points_array,0)
    row_y=np.size(means_array,0)
    z=np.sum(np.square(points_array),axis=1)
    t=np.sum(np.square(means_array),axis=1)
    d=np.sqrt(np.reshape(z,(row_x,1))+np.reshape(t,(1,row_y))-np.dot(points_array,means_array.T)*2)
    return d


# There are no local test for thus question, fill free to create them yourself.
# Feel free to play with it in a separate python file, and then just copy over
# your implementation before the submission.